spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-survey.c8zwh9jcttzy.ap-northeast-2.rds.amazonaws.com:3306/survey?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: allen
    password: daangnsurvey
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
