springdoc:
  swagger-ui:
   path: /api-docs
   display-query-params-without-oauth2: true
  paths-to-match: /api-docs
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ssdfasdftest