springdoc:
  swagger-ui:
   path: /api-docs
   display-query-params-without-oauth2: true
  paths-to-match: /api-docs
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ssdfasdftest

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-survey.c8zwh9jcttzy.ap-northeast-2.rds.amazonaws.com:3306?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: allen
    password: daangnsurvey

server:
  port: 5000